### ISSUE TITLE
How to add ES6 support?

### ISSUE THREAD

**Issue by coptup4ik** [cvgellhorn/webpack-boilerplate#110]
Hi. I am not very familiar of setting webpack config. I downloaded yours and it seems it is using es5 config .
How to add es6 support?
Thank you

**Comment by coptup4ik** [comment]
`client:162 ./app/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-react' from 'D:\Webpack_boilerplate'
    at Function.module.exports [as sync] (D:\Webpack_boilerplate\node_modules\resolve\lib\sync.js:43:15)
    at resolveStandardizedName (D:\Webpack_boilerplate\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePreset (D:\Webpack_boilerplate\node_modules\@babel\core\lib\config\files\plugins.js:58:10)
    at loadPreset (D:\Webpack_boilerplate\node_modules\@babel\core\lib\config\files\plugins.js:77:20)
    at createDescriptor (D:\Webpack_boilerplate\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at items.map (D:\Webpack_boilerplate\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (D:\Webpack_boilerplate\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (D:\Webpack_boilerplate\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (D:\Webpack_boilerplate\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)`
